### ISSUE TITLE
snakemake version issue

### ISSUE THREAD

**Issue by radio1988** [snakemake-workflows/chipseq#7]
Hello, 

I tried to use this workflow and ran into multiple issues, I guess it's related to the snakemake version:

If under 5.17.0

```
WorkflowError in line 37 of /project/umw_ingolf_bach/rui/final/chipseq/workflow/rules/peak_analysis.smk:
Extensions for multiext may not contain path delimiters (/,\) and must start with '.' (e.g. .txt).
  File "/project/umw_ingolf_bach/rui/final/chipseq/workflow/Snakefile", line 13, in <module>
  File "/project/umw_ingolf_bach/rui/final/chipseq/workflow/rules/peak_analysis.smk", line 37, in <module>
```

if version 6.4.1
```
MissingInputException in line 163 of /project/umw_ingolf_bach/rui/final/chipseq/workflow/rules/post-analysis.smk:
Missing input files for rule phantompeak_correlation:
../workflow/header/spp_corr_header.txt
```

Is this a snakemake version issue?  Snakemake seem to have trouble finding '../workflow' in the newer version, and it complained about syntax in the older version.

Which snakemake version was this tested on ? Thanks!

Ray

**Comment by dlaehnemann** [comment]
Hi Ray,

sorry, this whole workflow is still under heavy development as we finish porting all functionality from the [original nextflow workflow](https://nf-co.re/chipseq), which is why there is no release of this workflow, yet.

That said, I just merged a very big chunk of work in PR #6 and the newest version also includes automated testing. So the current latest version is dramatically different from 1 hour ago and should work. The snakemake report will just lack a lot of the descriptions for plots and other results, and some final output is still missing. But feel free to try out the newest version (which checks for `snakemake >= 6.4.0`) , just know that the first proper release is still a bit away.

Best,
David

**Comment by dlaehnemann** [comment]
Also, feel free to open other issues if you find new bugs. From the newest version on, the workflow should work, so we're interesting in hearing about any behaviour that is unexpected!

**Comment by radio1988** [comment]
Hello David,

Thanks a lot! The above issue disappeared with the update. I'll just need more time to adjust the configs. Do you think the workflow is ready for use? Do you have an estimation of when it will be ready for use? 

Thanks!

Ray

**Comment by dlaehnemann** [comment]
We're hoping to have something with a useable snakemake report in about a month, including proper descriptions of all the different outputs. And I think a useable report is the most important part to easily access the results. However, if you feel comfortable sifting through the results without those detailed descriptions and the report, you could probably use it as is and cross-check with the [output descriptions of the original nextflow workflow](https://github.com/nf-core/chipseq/blob/master/docs/output.md).

And no matter if you use this now or later, don't hesitate to open issues for questions and bugs!
